# Generated by Django 4.1.1 on 2022-09-25 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[], default={}, max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Кількість')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва квитка')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ціна квитка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tickets/img/', verbose_name='Зображення квитка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис квитка')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення квитка')),
                ('day', models.DateField(verbose_name='Дата проведення')),
                ('time', models.TimeField(verbose_name='Час проведення')),
                ('place', models.CharField(max_length=255, verbose_name='Місце проведення')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Кількість')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення платежу')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Знижка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.ticket')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки в замовленні',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
